name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: job-artifacts-and-output/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./job-artifacts-and-outputs
      - name: Lint code
        run: npm run lint
        working-directory: ./job-artifacts-and-outputs
      - name: Test code
        run: npm run test
        working-directory: ./job-artifacts-and-outputs
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: job-artifacts-and-output/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./job-artifacts-and-outputs
      - name: Build website
        run: npm run build
        working-directory: ./job-artifacts-and-outputs
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo "script-file={}" >> $GITHUB_OUTPUT ";"
        working-directory: ./job-artifacts-and-outputs
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            job-artifacts-and-outputs/dist
            job-artifacts-and-outputs/package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."
